name: Label PR

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions: {}

jobs:
  label:
    name: Label PR
    permissions:
      contents: read
      pull-requests: write
    uses: sebastienrousseau/pipelines/.github/workflows/labeler.yml@7061363af0a1da9d60c5901bd2874ac83ff7e34e
