name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'

permissions: {}

jobs:
  security:
    name: Security
    permissions:
      contents: read
      security-events: write
    uses: sebastienrousseau/pipelines/.github/workflows/security.yml@d9cb8b34257036b6ed44a0333d4093f447c1b8cc
    with:
      language: 'go'
      severity-threshold: 'moderate'
