name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'

permissions: {}

jobs:
  security:
    name: Security
    permissions:
      contents: read
      security-events: write
    uses: sebastienrousseau/pipelines/.github/workflows/security.yml@41d9a0d3043c8a289cc06ac3a84e0ac1b1814b71
    with:
      language: 'go'
      severity-threshold: 'moderate'
